### ISSUE TITLE
ADMINISTRACIÓN-Columnas "Templates"

### ISSUE THREAD

**Issue by Mariamzo** [trend-it-mx/VW-proveedores-audi#15]
Las columnas están desfazadas:

<img width="897" alt="image" src="https://github.com/trend-it-mx/VW-proveedores-audi/assets/125086291/0095cf97-2aa9-4437-bf0f-ccf3628e43da">

**Comment by Vlad-TrendIT** [comment]
Resuelto con el deploy

**Comment by Mariamzo** [comment]
OK

<img width="700" alt="image" src="https://github.com/trend-it-mx/VW-proveedores-audi/assets/125086291/0cdac731-398b-4b80-83c5-3b9e73048c25">
