### ISSUE TITLE
ADMINISTRACIÓN-Carga Calendario

### ISSUE THREAD

**Issue by Mariamzo** [trend-it-mx/VW-proveedores-audi#8]
No avisa que la carga fue exitosa en “Carga calendario”:

![image](https://github.com/trend-it-mx/VW-proveedores-audi/assets/125086291/e0905f69-54b7-4561-9374-d5070891ba9b)

**Comment by Vlad-TrendIT** [comment]
Cuando puedas me pasas un archivo de carga de calendario?

**Comment by Mariamzo** [comment]
[calendario_VW_2023.csv](https://github.com/trend-it-mx/VW-proveedores-audi/files/11916834/calendario_VW_2023.csv)

**Comment by Mariamzo** [comment]
La aplicación aún no avisa que la carga fue exitosa en “Carga calendario”:

**Comment by Mariamzo** [comment]
La aplicación aún no avisa que la carga fue exitosa en “Carga calendario”:

<img width="727" alt="image" src="https://github.com/trend-it-mx/VW-proveedores-audi/assets/125086291/39789742-7c2f-44b3-ba14-19a458f1f50a">
